theme: jekyll-theme-dinky
![](https://github.com/Briggskm9/Briggskm9.github.io/blob/main/images/17457382_10212451426348968_1862182588505706918_n.jpg)
title: Welcome
description:  to Katie's data science portfolio!
