theme: jekyll-theme-dinky
title: Welcome
description:  to Katie's data science portfolio!
description:  Hi everyone.  I am Katie Briggs and I am an Information Technology 
Project Manager currently living in the Dallas/Ft. Wort Metroplex. 
I love data and learning.  I also enjoy hiking, camping, olympic weightlifting and gardening. 
